-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 24, 2021 at 06:31 PM
-- Server version: 10.4.17-MariaDB
-- PHP Version: 7.4.13

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `vsga_jwd`
--

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--

CREATE TABLE `posts` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `excerpt` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `published_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`id`, `title`, `slug`, `excerpt`, `body`, `published_at`, `created_at`, `updated_at`) VALUES
(1, 'Kegiatan Pelaksanaan Sertifikasi Online', 'kegiatan-sertifikasi', '<p>Kegiatan Pelaksanaan Sertifikasi online dari Kominfo tahun anggaran 2021 oleh LSP Teknologi Digital.</p>', '<p>Kegiatan Pelaksanaan Sertifikasi online dari Kominfo tahun anggaran 2021 oleh LSP Teknologi Digital. Kegiatan akan di laksanakan mulai tanggal 13 September 2021 s/d 12 November 2021. Kegiatan dimulai dari pukul 08.00 s/d 15.00 WIB secara online melalui media zoom.\r\nRUNDOWN KEGIATAN</p>\r\n<br>\r\n    <p>1. Peserta mengerjakan project melalui google clasroom dengan kode kelas mfwvzmh untuk skema Junior mobile programmer, kode kelas omso5mm untuk skema Intermediate Multimedia Designer, kode kelas xvczr4r untuk skema Junior Grafic Designer, kode kelas 5dhn7su untuk skema Junior Web Developer dan kode kelas af7lckp untuk skema Junior Network Administrator. Pekerjaan/project dapat dikerjakan sebelum hari H pelaksanaan sertifikasi</p>\r\n    <p>2. Peserta mengisi formulir pendaftaran sertifikasi melalui sertifikasi.lspdigital.id atau LINK dengan melampirkan ktp, ijazah atau transkrip, sertifikat pelatihan atau surat keterangan. Pengisian dapat dilakukan sebelum hari H pelaksanaan sertifikasi</p>\r\n    <p>3. Pada tanggal pelaksaaan sertifikasi, peserta masuk melalui zoom dengan Meeting ID: 995 114 9640 Passcode: LSPTD</p>\r\n    <p>4. Peserta gabung ke breakout room sesuai dengan pembagian asesor(akan dipandu oleh admin)</p>\r\n    <p>5. Peserta mendemonstrasikan tugas praktek yang di instruksikan oleh Asesor</p>\r\n    <p>6. Peserta mengerjakan tes tertulis/lisan sesuai instruksi oleh Asesor</p>\r\n    <p>7. Asesor merekomendasi Kompeten atau Belum Kompeten</p>\r\n    <p>8. Peserta mengisi formulir umpan balik dan atau mengajukan banding</p>\r\n<br>\r\n<h6>TUTORIAL</h6>\r\n<br>\r\n    <p>1. Pendaftaran sertifikasi - LINK TUTORIAL</p>\r\n    <p>2. Bergabung ke Google Clasroom - LINK TUTORIAL</p>\r\n    <p>3. Menggunakan Zoom - LINK TUTORIAL</p>\r\n    <p>4. Tata Tertib - LINK DOWNLOAD</p>\r\n    <p>5. Group Telegram - LINK JOIN</p>\r\n    <p>6. Follow Instagram LSP TD - LINK IG</p>\r\n<br>\r\n<h6>KONTAK ADMIN</h6>\r\n<br>\r\n    <p>1. Agus Safitri - 0896-1725-7110</p>\r\n    <p>2. Muhammad Sutrisna - 0813-3364-3078</p>\r\n    <p>3. Iswadi - 0838-1127-7570</p>\r\n    <p>4. Samuji - 0878-7510-3344</p>\r\n    <p>5. Fiki Cahyanto - 0823-9934-9304</p>\r\n    <p>6. Roy Buana 085329489247</p>', NULL, '2021-09-18 01:42:22', '2021-09-18 01:42:22'),
(2, 'Fuga magnam vel neque quam harum et quaerat deleniti.', 'provident-assumenda-placeat-et-illum-assumenda', 'Dignissimos eum debitis ea vel. Itaque amet quis sit et id nostrum corrupti est. In illum harum vitae id error eos. Iusto ratione maiores sed eveniet.', '<p>Fuga est autem nesciunt quo voluptatum fugiat libero. Occaecati consequatur quia maxime nam velit alias quaerat. Et earum consectetur autem natus excepturi.</p><p>Sed aut cumque ea nulla et. Voluptatum provident officiis voluptate odit et provident et. Aut ratione et nulla velit culpa hic veniam. Ipsa maiores aperiam rerum quis.</p><p>Velit numquam eligendi qui aut corporis et voluptatem. Dolor ut neque est. Consequuntur cum animi quia incidunt.</p><p>Nihil suscipit dicta corporis maiores exercitationem. Est cum ut nostrum deserunt sunt est distinctio. Eius debitis sit doloremque. Soluta dolorem molestias perspiciatis.</p><p>Dolores et non et. Possimus sapiente voluptas ea facilis quia omnis qui. Rem possimus dolores eos soluta.</p><p>Quae occaecati possimus facilis pariatur quo nisi aut. Repudiandae voluptates veniam iste aliquam corporis. Eum maiores dolorum harum est.</p><p>Quibusdam repudiandae voluptatibus et animi velit dicta. Quia facere deleniti veniam quibusdam incidunt asperiores. Sunt nam nisi ipsam excepturi. Pariatur eveniet porro earum aut.</p>', NULL, '2021-09-18 01:42:22', '2021-09-18 01:42:22'),
(3, 'Eaque perferendis autem repellat unde dolore tempore.', 'possimus-est-aliquid-aperiam-hic-nulla-et', 'Quis explicabo aut dignissimos quia similique veniam. Odio quo aut ipsa facilis nam laborum. Dolorem ducimus porro rem ut sit nostrum ex. Fuga doloremque numquam cupiditate maxime. Vel voluptatem ex quo praesentium consequuntur quisquam repellat.', '<p>Odio eius et non non. Consequuntur ad dolores placeat deserunt autem consectetur. Nemo assumenda et quo voluptatem optio. Et quia in est et.</p><p>Est ullam eos odio consequatur in. Hic excepturi dolor accusantium mollitia magni. Nobis commodi et eligendi odit minus nam.</p><p>Sunt repudiandae ut autem vel. Est consequuntur ad ratione magnam eos tempore quia impedit. Aut sed accusantium voluptatem explicabo officia delectus.</p><p>Incidunt repellat maiores et autem tempora. Iure eius quis et tenetur est delectus. Repellat sint laudantium ullam fugiat.</p><p>Modi numquam unde fuga dolorum voluptatem eum culpa. Rem nostrum rerum tempore architecto dolorum. Nesciunt suscipit aut vitae facilis sint. Nihil porro autem consectetur rerum qui.</p><p>In sequi similique porro iste facilis ea exercitationem. Est quisquam totam temporibus voluptatem. Dicta optio atque vitae id ut.</p><p>Illum neque molestiae mollitia. Sed ut iure libero cum repellendus. A est consequatur vel doloremque.</p><p>A nobis delectus sit odio. Quibusdam consequatur dolores animi quia veritatis.</p><p>Et id fugit molestiae et quis quo. Temporibus voluptatem quidem consequatur saepe voluptatem quisquam cumque. Aut perspiciatis laboriosam earum repudiandae sunt laudantium. Rerum debitis voluptatem voluptas enim veritatis.</p><p>Modi sit aliquid delectus enim veritatis quis. Quo ducimus et quisquam qui. Omnis dolor ipsam et nobis minima. Non expedita cumque tempore et ex placeat.</p>', NULL, '2021-09-18 01:42:22', '2021-09-18 01:42:22'),
(4, 'Ipsum consectetur qui tenetur est quo.', 'nihil-sunt-unde-modi-nam-rem', 'Quis praesentium quia eligendi voluptate voluptatem ut. Et commodi autem sequi recusandae maiores ipsam. Sint rerum adipisci est voluptas omnis sequi accusantium qui. Odio voluptates ad possimus aut ut.', '<p>Impedit et beatae eos. Architecto corrupti ad veniam sed iure. Placeat qui perspiciatis in alias culpa et accusamus. Omnis libero repellendus qui libero voluptatem molestiae odio.</p><p>Delectus soluta fugiat minus rem. Iure alias qui aut nulla inventore temporibus. Officiis omnis eum quas omnis dignissimos. Incidunt qui repudiandae fuga dolor nihil necessitatibus quia.</p><p>Sed aut rerum velit dicta laborum adipisci consequatur iusto. Quis qui dolores quas quod voluptatem expedita. Temporibus molestiae minus quo iure.</p><p>Ut sint consectetur harum nam illum ullam aliquam. Suscipit optio reiciendis repellat. Nostrum molestiae laborum sunt eum possimus facilis.</p><p>Et id quia culpa voluptatem. Ea reiciendis labore omnis porro delectus illo est. Nesciunt quod qui atque velit. Tempora at exercitationem dolor qui.</p><p>Voluptatem enim voluptas odio ipsam. Totam qui quia eaque possimus. Impedit quam quibusdam non autem. Velit nemo velit iusto consectetur ex corrupti ipsum. Accusamus provident est sint ipsam.</p>', NULL, '2021-09-18 01:42:22', '2021-09-18 01:42:22'),
(5, 'Est magnam.', 'eaque-et-aperiam-est-numquam-repudiandae-eos-sit', 'Neque magni veritatis consectetur dolorem odit dolores. Cumque omnis consequatur aliquid qui eligendi dolorum ut sed. Necessitatibus aut ut debitis velit. Dolor aut perspiciatis nostrum ab tempore nostrum pariatur.', '<p>Voluptas est officiis officia necessitatibus. Omnis nihil fugiat sequi voluptas corrupti blanditiis perspiciatis. Id dolorem corporis nisi consectetur et dicta soluta. Accusamus est molestias sit occaecati quibusdam fugiat natus.</p><p>Ratione consequatur et aliquid alias. Libero ut temporibus consequatur officia quibusdam tenetur repellendus qui. Est quos eos minima earum cum. Architecto quis maxime molestias corrupti voluptatem consequatur qui. Sunt aspernatur aut nulla quasi ea.</p><p>Sint magni quibusdam officiis quaerat. Molestiae nulla optio magni similique molestiae id consequatur vel. Rerum consequatur et nobis error.</p><p>Nihil quo voluptatum eligendi totam nulla est. Est dignissimos iusto nostrum ipsa perspiciatis.</p><p>Sapiente qui ullam et cum sed. Quos placeat et atque consequatur vero ut. Repudiandae et magni consectetur exercitationem assumenda at quo. Ex omnis vel consequatur voluptates dicta dolorum in.</p><p>Sunt illo iste molestias ut enim. Cum nostrum molestiae tempore. Rerum qui voluptatem autem fugiat voluptas. Nostrum beatae dolor molestiae earum qui quibusdam nihil cumque.</p><p>Quia impedit iure tempore aliquid. Asperiores quae voluptatibus qui quo quia consectetur magni. Quasi molestiae id in doloremque aut provident. Nulla doloremque impedit neque eaque magni tempore.</p>', NULL, '2021-09-18 01:42:22', '2021-09-18 01:42:22'),
(6, 'Aut saepe harum ut officia sint atque voluptate.', 'ipsa-repellendus-et-sint-est-molestias', 'Necessitatibus aut harum voluptates blanditiis omnis. Temporibus ratione ut in atque debitis. Est eligendi iure eos dolores possimus voluptatibus dolorem. Maiores qui et rem illo vel aliquam.', '<p>Et atque facere quia enim eligendi. Vero facilis velit unde voluptas excepturi reiciendis id officiis. Ipsa et deleniti iusto omnis. Tenetur quis in voluptate.</p><p>Sed aliquam libero eius sed voluptatibus iure repellendus. Libero error magni recusandae tempora non qui quod. Dolorum quisquam libero quia harum.</p><p>Iure et suscipit possimus rem fuga repellendus ut et. Quo fuga autem qui quis ut quam hic. Et iusto eaque similique et esse aut dolor.</p><p>Et vitae vel molestiae non. Tenetur quae officia nemo aut. Totam pariatur sint consequatur. Maxime distinctio quae repellendus autem vitae dolor voluptas.</p><p>Harum dolore rerum laborum voluptatem dolore iste ut ducimus. Omnis ea mollitia vel repellat nemo inventore. Autem sint minus et qui ea id placeat.</p><p>Ipsa et quia tempore praesentium ut. Sunt quia ipsa inventore officiis maiores et. Veritatis earum explicabo tempore quidem reprehenderit atque.</p><p>Molestiae quasi praesentium nemo omnis possimus fuga exercitationem. Suscipit amet animi sit suscipit. Pariatur fugiat quo non fugit voluptatem est.</p><p>Ad odio consequatur blanditiis quo eaque molestiae debitis itaque. Sequi perspiciatis tempore modi asperiores sit. Ea doloremque earum temporibus.</p><p>Doloribus ad aliquam non natus. Deserunt qui et ut. Voluptatibus voluptate officiis non quisquam esse officia corrupti.</p><p>Voluptates sapiente ducimus pariatur aliquid maxime quidem. Impedit deserunt ea veritatis deleniti dignissimos est.</p>', NULL, '2021-09-18 01:42:22', '2021-09-18 01:42:22'),
(7, 'Mollitia asperiores perferendis laborum.', 'facere-quibusdam-voluptas-autem-vitae-quod-dolores', 'Voluptatem aut laborum ipsum sint labore. Sequi explicabo quasi maiores excepturi ut suscipit.', '<p>Qui aut asperiores dolore quia est velit. Commodi dolor molestiae et totam ex repellat facilis at. Repudiandae et adipisci vero et enim. Maxime non harum ducimus vel eaque impedit dolore ullam.</p><p>Rerum veniam ab in magnam. Suscipit illo sint ut aliquam eos veritatis qui est.</p><p>Est et voluptatibus asperiores nihil molestiae doloremque. Commodi deserunt non voluptate similique odit illum. Exercitationem ea et tenetur nobis quo aut numquam. Aut quis aliquid sint fugit.</p><p>Labore reprehenderit voluptas est perspiciatis odit. At numquam ipsam natus. Eum soluta nihil labore sed. Harum minus vel ut pariatur omnis.</p><p>Accusantium at est iure itaque temporibus laudantium. Eos rem id in. Maxime hic ducimus qui est nulla. Reiciendis in tenetur eos id facere non occaecati.</p><p>Eligendi sunt ea qui quia harum et vel. Vitae voluptatum aut velit sit provident non. Facilis sed officia et quo beatae officia. Non excepturi iusto qui recusandae reiciendis et voluptatem minus.</p><p>Maxime est odit rerum est voluptatum. Vel quibusdam officiis eos error voluptatibus.</p><p>Alias unde temporibus quia neque. Doloribus qui porro in et occaecati assumenda. Quia ipsa enim animi illum. Tempora et iure libero inventore et illum.</p>', NULL, '2021-09-18 01:42:22', '2021-09-18 01:42:22'),
(8, 'Molestiae facilis sequi.', 'assumenda-esse-aliquam-dolore-facere-labore-ut-rerum', 'Voluptatum tenetur est aperiam est iure et. Ut qui neque ex ea quia enim libero. Consectetur quidem quod quo optio tenetur sunt animi. Nam quia nihil ad minima quis sit.', '<p>Ipsa non animi facilis quas. Et in sapiente a. Omnis minus assumenda voluptatem voluptas temporibus vitae. Sint est reiciendis maiores id consequuntur neque fuga.</p><p>Ut impedit sed quaerat reprehenderit. Aliquid eum minus adipisci magnam assumenda aut. Eveniet aut natus sunt suscipit. Quis excepturi facere voluptatem. Reprehenderit quidem incidunt cum eos eum totam.</p><p>Aut hic aliquam sequi soluta. Iste asperiores ut exercitationem aut ab labore rerum. Molestias perspiciatis incidunt iste hic eligendi.</p><p>Voluptas odit quia temporibus qui odio. Quidem odit dolorum quam. Saepe voluptatem quia ab qui. Non velit iusto et eos natus aut. Omnis perspiciatis ut sed provident quibusdam ut dolor.</p><p>Rerum itaque voluptas ut molestiae. Soluta et corrupti illum praesentium et molestiae. Reprehenderit quod voluptatem esse rem expedita.</p><p>Dicta dicta quos sit non exercitationem. Libero qui sequi sit. Veritatis quia aut voluptate nostrum.</p><p>Similique itaque molestias velit eaque qui ipsum autem. Expedita perferendis molestiae ipsa. Officia aut dolorem dolor enim necessitatibus.</p>', NULL, '2021-09-18 01:42:23', '2021-09-18 01:42:23'),
(9, 'Recusandae sit nemo at impedit ut quasi sit.', 'est-itaque-et-officia-porro', 'Ut sapiente sunt ut magnam aut. Sit ipsam error nihil qui non libero tempore eligendi. Quis exercitationem et quo odit consequatur.', '<p>Qui aperiam consequuntur eligendi quos facilis repellat temporibus rerum. Inventore est fugiat magni quam. Dolor dolore enim exercitationem. Ea facilis quia ipsam sed excepturi nemo voluptatem.</p><p>Et voluptas atque aut enim. Voluptate molestiae suscipit velit vero labore. Voluptatem sunt magnam odio. Quis voluptatem reiciendis labore quae quia et.</p><p>Qui aut quia molestiae distinctio quas rerum natus. Soluta aut incidunt sunt. Voluptate temporibus id maxime at. Quos quo cumque rerum et ut eum dolor accusamus.</p><p>Dolorem vero nulla et voluptatem ut ut. Dignissimos nostrum fugit est a. Eum totam quidem explicabo et eaque.</p><p>Impedit in vel voluptas omnis omnis. Doloribus odit est in tempora tenetur ea alias. Accusamus dicta facere optio sequi nesciunt porro voluptas. Iusto reprehenderit sint nobis sed quos.</p><p>Hic explicabo possimus vel vel ratione. Odit magni inventore aut quia sapiente eaque consequuntur. Ullam neque culpa aliquid deleniti nihil et.</p><p>Molestias alias voluptatem officiis magni. Et rerum id voluptas perspiciatis veniam. Veniam et voluptas non ut enim cumque molestias.</p><p>Beatae explicabo et nobis labore rerum fuga. Id adipisci facilis similique cumque non dolor numquam laudantium. Facere iusto illum quia. Et ut eum ut. Commodi omnis animi sapiente fuga ea dicta.</p><p>Dolorem a a voluptatem voluptatem quisquam eos consequatur. Officiis ullam corrupti sed ipsam. In nihil distinctio quidem. Dolores dolorum eaque et aut sit laudantium harum.</p><p>Iste assumenda dolorum dolorem praesentium neque hic. Repellat iste sapiente ullam dolor quam non ut doloremque. Deserunt culpa dolores expedita omnis ea magni.</p>', NULL, '2021-09-18 01:42:23', '2021-09-18 01:42:23'),
(10, 'Quibusdam et minus non alias.', 'sunt-odit-tenetur-vel-incidunt-et-velit-architecto', 'Vel debitis non in pariatur repudiandae odit. Voluptates commodi sunt veritatis veritatis ut amet. Non aut quia dolores possimus.', '<p>Aut a laboriosam est aspernatur pariatur voluptas quibusdam. Sed ipsam iure totam voluptatem incidunt similique et. Facere at qui voluptas magnam recusandae. Laudantium qui vel atque minus dolorem sed.</p><p>In deserunt dolor quasi culpa ipsa laudantium natus. Voluptas qui voluptatibus aut est. Temporibus fugit excepturi assumenda omnis incidunt corporis. Reprehenderit quidem architecto facere maiores quos ratione quia.</p><p>Alias optio inventore hic voluptas. Amet qui laborum non eum laboriosam.</p><p>Laboriosam qui ad exercitationem voluptatem aut. Mollitia veritatis nemo voluptatem. Iure sint tenetur eos dolores expedita.</p><p>Doloribus sed quam a. Corrupti et ut ut. Cupiditate maxime reprehenderit necessitatibus repudiandae modi qui est.</p><p>Illo at repellat tempora similique. Nisi est soluta ut labore. Porro sed eum fugiat iste nobis odit. Consequatur quasi nemo quis incidunt velit qui.</p><p>Iste aut iusto eius quis quas necessitatibus. Qui temporibus qui facilis et. Ab est at odit eveniet qui. Necessitatibus possimus alias maiores repellat et sequi.</p><p>Quasi quaerat illum labore repellendus nemo. Quia magnam sed quia nostrum. Est et a quis qui reiciendis. Et omnis quo ducimus quia.</p><p>Doloremque eos ut reprehenderit accusantium incidunt. Consequatur voluptas quod nesciunt nobis deleniti corrupti et. Architecto amet ut molestiae placeat aliquid repellat qui voluptas. Quis provident optio et.</p>', NULL, '2021-09-18 01:42:23', '2021-09-18 01:42:23'),
(11, 'Nam et et recusandae ut ducimus consequuntur non.', 'consequatur-debitis-voluptatem-qui-qui-veniam-minima', 'Similique qui velit voluptas. Dolore quod quia incidunt voluptate vero fugiat. Officia dolores quo consectetur a beatae omnis natus. Harum ad facere veritatis.', '<p>Ut alias perferendis earum. Et dolor totam itaque dolorem id et.</p><p>Nulla dolore recusandae quia eligendi velit cumque hic est. Ut praesentium ut eius. Aliquam voluptatem dolorum consequatur in dolorem.</p><p>Fugit aliquid ea numquam impedit non ex. Eos tenetur voluptas sit dolor fuga. Suscipit in iusto tenetur non omnis rerum corrupti. Autem voluptatum magni est aperiam qui autem veniam.</p><p>Architecto quo saepe mollitia est eius sunt qui sint. Atque placeat ducimus recusandae non nobis explicabo ea autem. Harum quo non sint et.</p><p>Dignissimos repudiandae et pariatur minima eos. Asperiores quia accusamus porro ducimus hic. Ipsum et voluptatem consequatur.</p><p>Inventore sunt inventore maxime occaecati officiis consequatur. Harum libero nam cumque quae illo neque iure. Exercitationem asperiores temporibus deserunt ut repellendus error quos. Aut et animi dolores ut. Facere ut et quaerat esse nam accusamus et.</p><p>Necessitatibus est labore aliquid fugiat omnis harum sunt ullam. Praesentium voluptas aut facere aperiam. Et consequuntur minus quia non voluptatem repudiandae. Sed dolorem saepe dolores dolore.</p><p>Voluptatem tempore blanditiis earum quo libero. Voluptates velit dolores occaecati eum doloremque repudiandae ipsum. Ut sint nobis maxime voluptates quia facere excepturi. Veritatis ut ea ducimus accusamus. Dolor est eum dolore quibusdam dicta molestiae.</p>', NULL, '2021-09-18 01:42:23', '2021-09-18 01:42:23'),
(12, 'Dolorum provident consequatur.', 'voluptate-excepturi-saepe-ipsa-cum', 'Et error unde temporibus aspernatur. Ea sed voluptas numquam provident. Tempore corrupti animi rem. Atque ad vero sed impedit perspiciatis aut eum.', '<p>Et illum assumenda et distinctio. Dolor esse necessitatibus temporibus sed soluta odit est. Ut et nisi fuga et similique dolor quis. Blanditiis dolores totam sit sit qui beatae cupiditate.</p><p>Animi aperiam illo inventore dignissimos. Ipsum cumque distinctio iste hic quod harum minima illo. Maxime fugiat ipsam assumenda vel. Recusandae harum quia esse.</p><p>Saepe aut pariatur sed illum iure corrupti. Dignissimos fuga voluptatem dolor. Et velit ab et ipsa repellat fugit eaque harum. Asperiores ut odit quisquam excepturi iusto aut.</p><p>Et qui architecto aliquam ducimus impedit. Suscipit consequatur rerum fugit eius quis minus et. Perspiciatis quam architecto animi quia. Ut dicta nam qui enim.</p><p>Ea nihil eum ut beatae officia ut pariatur. Dolor dolor nemo fugiat sunt commodi rem eum velit. Totam ipsa cumque accusamus. Cum esse voluptatibus ipsam omnis nihil harum. Et maiores voluptatem aliquam non cum rerum in.</p><p>Laudantium accusantium repudiandae eum quidem temporibus. Facere atque et magni in rem. Corrupti delectus pariatur nihil nostrum molestiae. Beatae quam facere maiores nemo.</p><p>Omnis voluptatum minus et molestiae ullam corporis excepturi id. Distinctio qui fuga natus qui. Distinctio quo sunt eveniet debitis velit. Et vero culpa quo rerum eum quis sit. Quasi nobis praesentium est id qui exercitationem consequatur nesciunt.</p><p>Blanditiis officiis cum et. Enim fuga eos in ut. Eum culpa ab voluptates rerum. Voluptatum dolor necessitatibus facilis eius eos voluptatum repellat.</p>', NULL, '2021-09-18 01:42:23', '2021-09-18 01:42:23'),
(13, 'Rerum similique suscipit quia sed eaque nemo sunt.', 'officiis-voluptatem-autem-autem-aut', 'Nemo et in vero. Quis sunt animi facilis expedita in. Qui est iste dolorum exercitationem illum quo. Quisquam quaerat consequuntur voluptatum nihil dolore.', '<p>Ipsam dolorem ea nulla sint numquam suscipit sed. Ad iure minus eum laudantium porro est sapiente. Laudantium tempore nihil exercitationem ea quia et.</p><p>Dolorum debitis eos non et voluptatem odit. Est itaque deserunt nulla repellendus.</p><p>Ratione ut omnis earum rerum nobis dicta at. Velit delectus temporibus aut earum. Eaque voluptas quis ad eum voluptatem tenetur. Totam optio adipisci aut et adipisci.</p><p>Consequuntur iusto officia mollitia eius. Iure rerum nihil occaecati illum tenetur voluptas. Veritatis facilis cumque quod distinctio est.</p><p>Enim laudantium dolores dicta animi ipsa eaque. Illo corrupti in voluptatibus quo hic. Occaecati voluptate nostrum impedit laudantium magnam rerum. Soluta debitis totam blanditiis voluptas temporibus iste corrupti in.</p>', NULL, '2021-09-18 01:42:23', '2021-09-18 01:42:23'),
(14, 'Harum et sequi voluptas magni accusantium molestiae delectus.', 'eum-quisquam-vitae-voluptatibus-accusantium-fuga-voluptas-aut', 'Neque aut excepturi voluptatibus tempore. Perferendis cum excepturi fugiat corporis. Doloremque voluptates unde sunt et sint aspernatur. Hic vitae at est mollitia illum.', '<p>Fuga doloribus nostrum similique temporibus similique occaecati quibusdam. Quia autem perspiciatis autem consectetur et. Occaecati dolorum doloribus tempore maiores voluptas et. Omnis numquam modi id sequi.</p><p>Cupiditate reiciendis quasi earum laboriosam. Quibusdam doloribus animi rerum et accusamus qui. Delectus repudiandae facilis minima vel aperiam ut.</p><p>Temporibus et vero dicta quia commodi culpa natus atque. At et eum consequatur. Ipsam odit distinctio eligendi quibusdam maiores eos fugit.</p><p>Et aut et eius et dolores saepe. Optio atque qui ipsa alias quos quaerat vero. Exercitationem est doloremque dolor. Odio sint enim consectetur tenetur molestiae.</p><p>Earum est ut eum ut accusamus rerum id. Quis et assumenda et esse sed est. Quisquam perferendis enim aut eveniet sit adipisci unde. Accusantium molestiae ratione est commodi est aliquid ea.</p><p>Cupiditate voluptas aperiam voluptates eveniet officiis placeat vel et. Est neque vel et neque omnis laboriosam et nesciunt. Dolor aut ipsam tempore ut iure eum.</p>', NULL, '2021-09-18 01:42:23', '2021-09-18 01:42:23');

-- --------------------------------------------------------

--
-- Table structure for table `skema`
--

CREATE TABLE `skema` (
  `id` int(5) NOT NULL,
  `nama_skema` varchar(100) NOT NULL,
  `penjelasan` varchar(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `skema`
--

INSERT INTO `skema` (`id`, `nama_skema`, `penjelasan`) VALUES
(1, 'Digital Marketing', 'Melakukan aktivitas promosi untuk sebuah produk atau brand menggunakan media Digital.'),
(2, 'Network Administrator Muda', 'Profesi terkait skema ini antara lain Network Engineer, Sys admin, IT Network, IT Infrastructure dsb.'),
(3, 'ICT Project Manager', 'Profesi terkait ini antara lain Project dan Supervisor Manager, Business Development Manager, Scrum dll.'),
(4, 'Junior Web Developer', 'Profesi terkait skema ini antara lain Web Programmer, Mobile programmer, Front end Programmer .');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `posts_slug_unique` (`slug`);

--
-- Indexes for table `skema`
--
ALTER TABLE `skema`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `posts`
--
ALTER TABLE `posts`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;

--
-- AUTO_INCREMENT for table `skema`
--
ALTER TABLE `skema`
  MODIFY `id` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
